some changes
eProsima/SOSS-docs pull request #4
Opened 2020-05-05 12:32 UTC by FranFin

2020-05-05 13:51 UTC, LuisGP requested changes

2020-05-05 13:51 UTC, LuisGP commented on docs/external_dep.rst
> +* `eProsima Fast-RTPS <https://github.com/eProsima/Fast-RTPS/>`__
Fast-RTPS isn't a SOSS dependency. It's a SOSS-DDS dependency only.

2020-07-09 13:01 UTC, richiware commented
Buildstatus:[![BuildStatus](http://jenkins.eprosima.com:8080/buildStatus/icon?job=soss_docs_manual&build=1)](http://jenkins.eprosima.com:8080/job/soss_docs_manual/1/)

2020-07-10 06:26 UTC, LuisGP approved these changes

2020-07-10 06:26 UTC, merged